#ifndef TRANSACTION_TYPES_H
#define TRANSACTION_TYPES_H

// Transaction type enumeration
typedef enum {
    TRANSACTION_BALANCE_CHECK,
    TRANSACTION_DEPOSIT,
    TRANSACTION_WITHDRAWAL,
    TRANSACTION_PIN_CHANGE,
    TRANSACTION_MINI_STATEMENT,
    TRANSACTION_MONEY_TRANSFER,
    TRANSACTION_CARD_REQUEST
} TransactionType;

#endif // TRANSACTION_TYPES_H